export const MOVIES = {
  SEARCH: 'SEARCH_MOVIES',
  SEARCH_RESET: 'SEARCH_MOVIES_RESET',
  LOAD_SUCCESS: 'LOAD_MOVIES_SUCCESS',
  TITLE: 'GET_PAGE_TITLE',
  INIT_SEARCH: 'INIT_SEARCH_PROPS',
  REQUEST: 'LOAD_MOVIES_REQUEST',
  FAILURE: 'LOAD_MOVIES_FAILURE',
  SET_PAGE: 'SET_PAGINATION',
};

export default MOVIES;
