export const MOVIES = {
  SEARCH: 'SEARCH_MOVIES',
  SEARCH_RESET: 'SEARCH_MOVIES_RESET',
  LOAD_SUCCESS: 'LOAD_MOVIES_SUCCESS',
  TITLE: 'GET_PAGE_TITLE',
  SEARCH_QUERY: 'GET_SEARCH_QUERY',
  REQUEST: 'LOAD_MOVIES_REQUEST',
  FAILURE: 'LOAD_MOVIES_FAILURE',
};

export default MOVIES;
