export const MOVIES = {
  SEARCH_MOVIES_RESET: 'SEARCH_MOVIES_RESET',
  LOAD_MOVIES_SUCCESS: 'LOAD_MOVIES_SUCCESS',
  INIT_SEARCH_PROPS: 'INIT_SEARCH_PROPS',
  LOAD_MOVIES_REQUEST: 'LOAD_MOVIES_REQUEST',
  LOAD_MOVIES_FAILURE: 'LOAD_MOVIES_FAILURE',
  SET_PAGE: 'SET_PAGE',
};

export default MOVIES;
